### ISSUE TITLE
能否使用IDA7.7或8.0的SDK编译一个

### ISSUE THREAD

**Issue by RandLily** [fjqisba/E-Decompiler#11]
如题

**Comment by fjqisba** [comment]
难道不兼容吗？应该是一样的吧，我手里头没有高版本的sdk

**Comment by RandLily** [comment]
目前泄露的IDA最新是7.7，IDA8.0的SDK在看雪也发布了
经过测试大佬您发布的测试版0.3能在7.7正常使用，之前的0.2不可以

**Comment by yjd** [comment]
测试52最新的8.3也正常
